### ISSUE TITLE
Schema: aten::softplus(Tensor self, Scalar beta=1, Scalar threshold=20) -> (Tensor)

### ISSUE THREAD

**Issue by TorRient** [NVIDIA/TRTorch#213]
Converter for aten::softplus requested, but no such converter was found
I am having the above problem!
Can you fix it?

**Comment by peri044** [comment]
softplus activation is not natively supported by TensorRT. So there is no converter in TRTorch. However, there are two ways to add a converter.

1) Express it as a composition of TensorRT ops.
  ```
  SoftPlus (SP) = (1/beta)*log(1 + exp(beta*x)) = -(1/beta)* log(sigmoid(-beta*x))
  # To incorporate threshold, we can compute a boolean mask = SP > threshold
  Final output = mask*x + (inverted_mask)*SP
  ```
2) Write a plugin with a softplus kernel 
    References to serve as examples: [TensorRT Leaky Relu kernel implementation](https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/kernels/lReLU.cu), [Pytorch Softplus layer call](https://github.com/pytorch/pytorch/blob/7731370e718ad16994d8da25fbdc9de64a22ec44/aten/src/ATen/native/cuda/Activation.cu#L284), [Pytorch softplus kernel implementation](https://github.com/pytorch/pytorch/blob/3796cbaf7ab4c4c30cb99191d55a8b9c50b398dc/caffe2/operators/softplus_op.cu#L7)
  
    We have an example on how to integrate a custom kernel into a layer which can be converted in TRTorch. You need to write a 
    plugin and add your softplus kernel. You can follow the interpolate plugin for example.

- [(https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.h](https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.h)
- [https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/interpolate.cpp](https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/interpolate.cpp)

Probably option 2 might be faster since everything is fused in a single kernel.
