### ISSUE TITLE
✨[Feature] Support torch.to to move data from cpu to gpu

### ISSUE THREAD

**Issue by inocsin** [NVIDIA/TRTorch#409]
FunctionSchema:

to.dtype_layout(Tensor self, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, bool non_blocking=False, bool copy=False, MemoryFormat? memory_format=None) -> Tensor

to.device(Tensor self, Device device, ScalarType dtype, bool non_blocking=False, bool copy=False, MemoryFormat? memory_format=None) -> Tensor

I have tried to compile model with subgraph as below, one CONSTANT value was stored at cpu, so the subgraph tried to use aten::to to copy data from cpu to gpu
```
_115 = torch.view(torch.repeat(CONSTANTS.c2, _114), [-1, 1, 1])
rep_mean = torch.to(_115, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False, non_blocking=False, copy=False)
_119 = torch.sub(input4, rep_mean, alpha=1)
```

Currently, aten::to https://github.com/NVIDIA/TRTorch/pull/382 was not merged yet, and the function metioned above should be supported to compile this subgraph.

Error logs:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
" thrown in the test body.
```

**Comment by narendasan** [comment]
The expectation currently expects models that are already on GPU. so users should be doing `model.cuda()` before compilation. Are there models that wouldn't fit this expectation?

**Comment by inocsin** [comment]
> The expectation currently expects models that are already on GPU. so users should be doing `model.cuda()` before compilation. Are there models that wouldn't fit this expectation?

Model's weights can be moved from CPU to GPU by model.cuda(), but the CONSTANTS are still stored in cpu.

**Comment by narendasan** [comment]
Can you provide more graph context here? You would see similar errors in PyTorch iirc if a tensor was held on CPU but you tried to do an operation with tensors held on GPU. It seems like this might be an issue where a tensors is being created by evaluator and that tensor is on CPU

**Comment by inocsin** [comment]
> Can you provide more graph context here? You would see similar errors in PyTorch iirc if a tensor was held on CPU but you tried to do an operation with tensors held on GPU. It seems like this might be an issue where a tensors is being created by evaluator and that tensor is on CPU

```
_115 = torch.view(torch.repeat(CONSTANTS.c2, _114), [-1, 1, 1])
rep_mean = torch.to(_115, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False, non_blocking=False, copy=False)
_119 = torch.sub(input4, rep_mean, alpha=1)
```
Just like this case, the CONSTANTS values was stored in cpu, and there is no way to move this data from cpu to gpu. Model.to(torch::kCUDA) doesn't work here, it only move weights from cpu to gpu but the CONSTANTS was stored in script_model.code_with_constants[1].c0. Only aten::to can move this data from cpu to gpu in conversion phase. Please merge https://github.com/NVIDIA/TRTorch/pull/382 is PR, after that, I can implement this part

**Comment by narendasan** [comment]
Yeah I understand this, but it seems like what is happening here is: 

1. There is some constant `c2` which I dont know what the type of this is
2. using `c2` and whatever `_114` is (This is why I asked for more graph context) is used to create a Tensor using repeat
3. view reshapes this tensor
4. this tensor is moved to GPU
5. you do subtraction with this on GPU

How this should be handled in TRTorch right now is 
1. We get `c2` which is probably going to be some sort of an `IValue`
2. a repeat converter is going to take `c2` and `_114` and create a new Tensor (This should be handled properly by the converter, like `ITensorOrFreeze` will handle making `c2` a constant layer if its a `at::Tensor` which would "put it on the GPU") https://github.com/NVIDIA/TRTorch/blob/1f0a8cbb2134826ab00183757704482c54129602/core/conversion/converters/impl/expand.cpp#L228
3. We use the View converter to reshape the ITensor from repeat
https://github.com/NVIDIA/TRTorch/blob/36a5d975526d8cc9ef52f15352f5015264eeb08a/core/conversion/converters/impl/shuffle.cpp#L62
4. `.to` is not relevant here, the output `ITensor` from the repeat converter is already "on GPU"
5. We use the sub converter for the sub operation.  

Having .to doesnt seem relevant here since from the inputs to repeat to the inputs into sub all the data should be things we already handle properly or they will be ITensors where there is no notion of CPU tensors. Also #382 lowers out Device `.to` because I'm still not sure what the usecase for a CPU -> GPU operator is in the context of a TRT graph, so that won't do what you think it will.

This error also seems like its coming from LibTorch and not TRTorch, so I feel like there's something else going on here. I am not sure where it might show up since it seems like in this subgraph things should be handled. Do you have debug mode turned on? Can I get more of the logs? Is this from a test case you are writing or something?
