### ISSUE TITLE
error: ‘tryTypeMetaToScalarType’ is not a member of ‘c10’

### ISSUE THREAD

**Issue by AllentDan** [NVIDIA/TRTorch#449]
## ❓ CMake building error using this [repo](https://github.com/JosephChenHub/TRTorch)

How to build the TRTorch or use the release packages of TRTorch in Ubuntu 18.04?
## What you have already tried
Tried build TRTorch through CMakeLists.txt provided by [this](https://github.com/NVIDIA/TRTorch/issues/263).

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - OS (e.g., Linux):Ubuntu18.04
 - Build command you used (if compiling from source):cmake.. and make
 - Are you using local sources or building from archives:Yes
 - CUDA version:11.1
 - TensorRT version:7.2.3.4
 - Make error:
A bunch of warnings and then the error:
```
/home/SENSETIME/dongchunyu/dongchunyu/depends/TensorRT-7.2.3.4/include/NvInfer.h:3250:22: note: declared here
 class TRT_DEPRECATED IRNNv2Layer : public ILayer
                      ^~~~~~~~~~~
/home/SENSETIME/dongchunyu/dongchunyu/depends/TensorRT-7.2.3.4/include/NvInfer.h:5662:85: warning: ‘IPluginLayer’ is deprecated [-Wdeprecated-declarations]
  ITensor* const* inputs, int32_t nbInputs, IPluginExt& plugin) TRTNOEXCEPT = 0;
                                                                              ^
/home/SENSETIME/dongchunyu/dongchunyu/depends/TensorRT-7.2.3.4/include/NvInfer.h:3454:22: note: declared here
 class TRT_DEPRECATED IPluginLayer : public ILayer
                      ^~~~~~~~~~~~
/home/SENSETIME/dongchunyu/dongchunyu/codes/c++/tmp/TRTorch/core/util/trt_util.cpp: In function ‘c10::optional<nvinfer1::DataType> trtorch::core::util::toTRTDataType(caffe2::TypeMeta)’:
/home/SENSETIME/dongchunyu/dongchunyu/codes/c++/tmp/TRTorch/core/util/trt_util.cpp:270:21: error: ‘tryTypeMetaToScalarType’ is not a member of ‘c10’
   if (auto t = c10::tryTypeMetaToScalarType(dtype)) {
                     ^~~~~~~~~~~~~~~~~~~~~~~
/home/SENSETIME/dongchunyu/dongchunyu/codes/c++/tmp/TRTorch/core/util/trt_util.cpp:270:21: note: suggested alternative: ‘optTypeMetaToScalarType’
   if (auto t = c10::tryTypeMetaToScalarType(dtype)) {
                     ^~~~~~~~~~~~~~~~~~~~~~~
                     optTypeMetaToScalarType
CMakeFiles/util.dir/build.make:110: recipe for target 'CMakeFiles/util.dir/core/util/trt_util.cpp.o' failed
make[2]: *** [CMakeFiles/util.dir/core/util/trt_util.cpp.o] Error 1
CMakeFiles/Makefile2:219: recipe for target 'CMakeFiles/util.dir/all' failed
make[1]: *** [CMakeFiles/util.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

## Additional context
Wishing for official cmake tool!!!

**Comment by narendasan** [comment]
Hi @AllentDan, 

This is not a workflow that is supported by us. Can you try building with Bazel or are you required to use CMake?
Either way, seems like the issue is that you are using an old version of TRTorch with a new version of PyTorch. 
TRTorch made this change a while back to support a newer PyTorch release: https://github.com/NVIDIA/TRTorch/blob/0a3258dfadc4434218eb8da14a28f93727bf60c5/core/util/trt_util.cpp#L280

**Comment by narendasan** [comment]
If i had to guess, its due to additional subcomponents that have been added, the ir and partitioning subdirectories in core. I guess the old CMakeList.txt probably doesnt cover those

**Comment by AllentDan** [comment]
Hi, @narendasan. I tried to include new folders in core and cmake the project again. But when using the cmake output in new project, still got:
```bash
undefined reference to `trtorch::core::partitioning::Partition(std::shared_ptr<torch::jit::Graph>, std::vector<trtorch::core::ir::InputRange, std::allocator<trtorch::core::ir::InputRange> >&, trtorch::core::partitioning::PartitionInfo const&)'
```
It seemed that InputRange error fixed. But something still missed...

BTW, I also tried the bazzel version provided. But a bunch of other errors appeared:
```
lib/libtrtorch.so: undefined reference to `at::Tensor::to(c10::TensorOptions const&, bool, bool, c10::optional<c10::MemoryFormat>) const'
lib/libtrtorch.so: undefined reference to `at::full(c10::ArrayRef<long>, c10::Scalar, c10::TensorOptions const&)'
lib/libtrtorch.so: undefined reference to `c10::ClassType::create(c10::optional<c10::QualifiedName>, std::weak_ptr<torch::jit::CompilationUnit>, bool)'
lib/libtrtorch.so: undefined reference to `caffe2::detail::TypeMetaData const* caffe2::TypeMeta::_typeMetaDataInstance<bool>()'
```
Please give some advises... Thanks again.

**Comment by narendasan** [comment]
What is the method you used when trying bazel? What does your WORKSPACE file look like and what command did you use to compile?

**Comment by AllentDan** [comment]
Hi, really great job you have done!!!
I restarted using trtorch yesterday and solved above problems. I tried trtorch 0.3 you released both python and cpp and was surprised by its performace compared to torchscript and tensorrt. 

For cpp usage, trtorch depends on strict libtorch, cudnn and tensorrt version, which is the reason for my above errors. Hope it can be solved in the future.

BTW, I am trying to use trtorch to wrap pytorch c++ api models in my own projects. However, there is no way for me to convert torch::nn::Module to torch::jit::Module. You are more familiar with torchscript than me. Could you give some hints? It will be really appreciated for your kindly help.

**Comment by narendasan** [comment]
Great to hear you are seeing good results! For library versions, we will likely always be tied to specific pytorch versions because of how we integrate into the pytorch infra, maybe down the line these points will stabilize but it doesnt seem like it will happen soon. Versions of cudnn and TensorRT stem from our target PyTorch version's cuda and cudnn dependencies. If you have specific version requirements in your environment, the code is mostly TensorRT/cudnn version agnostic. Its really these specific pytorch integration points like `c10::optTypeMetaToScalarType` which cause incompatibilities between versions. At this point my best guidance is to look at the PRs bumping PyTorch versions to see the set of changes needed to be applied to the source.

As to how to get C++ nn::Modules into torchscript, I am not sure. I dont think ive ever really tried that workflow. the PyTorch Forums (https://discuss.pytorch.org/) might be a good place to ask.

**Comment by AllentDan** [comment]
Thanks for your kind reply. Wish trtorch goes better in the future. 😃
