### ISSUE TITLE
🐛 [Bug] Unable to parse functions in the forward pass (script mode)

### ISSUE THREAD

**Issue by SrivastavaKshitij** [NVIDIA/TRTorch#497]
##  Bug Description

TRTorch is unable to parse functions called in the forward pass in the script mode. 

## To Reproduce

Following sample code reproduces the issue with the following command : `python test.py`

test.py
```
import torch
import trtorch

class dummy_model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(3,3,3)

    @torch.jit.export
    def features(self,x):
        x = self.conv(x)
        return self.conv(x)

    def forward(self,x):
        #x = self.conv(x)
        x = self.features(x)
        return x

with torch.no_grad():
    model = dummy_model().eval().cuda()
    model = torch.jit.script(model)
    print("model scripted")
    input_t = torch.randn(1,3,224,224,device="cuda:0")

    out = model(input_t)
    print(out.size())

    compile_settings = {"input_shapes": [[1,3,224,224]],"op_precision": torch.float32}
    #model = torch.jit.freeze(model)
    model_trt = trtorch.compile(model,compile_settings)

    trt_out = model_trt(input_t)
    print(trt_out.size())

```

Error encountered:

```
model scripted
torch.Size([1, 3, 220, 220])
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    model_trt = trtorch.compile(model,compile_settings)
  File "/opt/conda/lib/python3.8/site-packages/trtorch/_compiler.py", line 73, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: Method 'features' is not defined.

```

If I uncomment `torch.jit.freeze` line in the above code, then conversion is fine. I assume Trtorch is unable to parse forward pass where the function calls are not inline. 

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - https://github.com/NVIDIA/TRTorch/blob/master/docker/Dockerfile.21.02

**Comment by sandeepkumar-skb** [comment]
Additional info: We are currently using `torch.jit.freeze` only as a work-around but its not intended to be used in the main work flow as it clones the network. This results in increasing the memory footprint.

**Comment by peri044** [comment]
@SrivastavaKshitij TRTorch is trying to compile methods like "features" and internally we perform jit freezing on the module. After we freeze the model, any methods other than forward are by default eliminated which is why we see this error. From my understanding, we don't need to compile "features" method separately, as the "forward" method includes all the layers and modules called in the graph.

So when I restrict TRTorch [here ](https://github.com/NVIDIA/TRTorch/blob/master/core/compiler.cpp#L260)to only compile "forward" method, this issue will be resolved. I've added this fix in the PR https://github.com/NVIDIA/TRTorch/pull/499 in core/compiler.cpp. Let me know if this works for you. I've ran your model in C++ and it works with this fix.

Just for info, uncommenting torch.jit.freeze in your python code works because that step eliminates the features method (as per the [doc](https://pytorch.org/docs/stable/generated/torch.jit.freeze.html)) so it won't be an issue to TRTorch. 

cc @narendasan Any drawbacks/limitations that you can think of by restricting it to compile only "forward" methods ?

**Comment by SrivastavaKshitij** [comment]
Yes, I can confirm that my script is working with PR #499 .

**Comment by narendasan** [comment]
I think that compiling forward is overly restrictive in general, but a workable workaround for now considering what the compile function has been doing to date. I think in the future we should be looking at compiling all methods that cannot be inlined but i think this would require the graph construction to be much smarter.

**Comment by SrivastavaKshitij** [comment]
So, it looks like we all agree with the solution, then, is it okay to merge the PR ? @peri044
