### ISSUE TITLE
How to use local pytorch instead of installing again.

### ISSUE THREAD

**Issue by alanzhai219** [NVIDIA/TRTorch#62]
Hi Naren,
glad to see that you check-in py binding and test. 
TRTorch needs to install pytorch and torchvision again and I know it is easy to build trt from scratch.
But as a developer, I always build and set pytorch env locally and do need to install it again. Could you help provide options to call local pytorch instead of installing again. @narendasan 

Thanks,
Alan

**Comment by narendasan** [comment]
Are you being required to install the pytorch package again when installing the wheel or running tests? 

In the bazel workspace bazel will set up its own copy for testing the library so we test hermetically against the version of PyTorch we compile against i don't think there is any way around that and I don't think it will mess up your PyTorch env, this is not used during building only testing. 

If you are being required during installation of the wheel to install another PyTorch (maybe because you have a custom build) I would suggest building from source, the TRTorch library should target the version of PyTorch you are using. You will need to modify the WORKSPACE so that the `libtorch pre-cxx11-abi` target is a local repository pointing to the `.so's` you built and the `requirements.txt` restrictions are relaxed in `//py/requirement.txt`. 1.5.0 is the current PyTorch release so we have not tested on any new build yet.

**Comment by alanzhai219** [comment]
I am sorry that I didn't describe it clearly.
When I try to build this project, type the command:
```
bazel build //:libtrtorch --compilation_mode=dbg
```

spend too much time fetching trtorch_py_deps and it always reports 'ERROR: An error occurred during the fetch of repository 'trtorch_py_deps' error because of network issue.
So, any way to install manually and skip such 'fetch' in Bazel script?

Thanks.

**Comment by narendasan** [comment]
I'm not sure if `--distdir` (https://docs.bazel.build/versions/master/guide.html#distribution-files-directories) will work for python wheels used in the dependencies, you can try it and see, otherwise the python deps are used only for testing, they can be safely disabled if you aren't running `//tests:python_api_tests`

**Comment by alanzhai219** [comment]
It doesn't work. 
Such py is hard to use for timeout or unstable network. 
Is there any way of build locally instead of download so many dependencies.
[Believe it or not, one-key build is not easy to build(for example, pytorch is easier to build than tensorflow). It is not user-friendly.]
Please help try to improve it. Thanks.

**Comment by narendasan** [comment]
You can remove those dependencies from the WORKSPACE they are only used for testing. 

Just remove the lines below, as long as your arent running python API tests you will not need them.
```
pip3_import(
    name = "trtorch_py_deps",
    requirements = "//py:requirements.txt"
)

load("@trtorch_py_deps//:requirements.bzl", "pip_install")
pip_install()

pip3_import(
    name = "py_test_deps",
    requirements = "//tests/py:requirements.txt"
)

load("@py_test_deps//:requirements.bzl", "pip_install")
pip_install()
```
